name: App Deploy
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: App Build
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'EOussama'
        reponame: 'playback-sync'
        token: ${{ secrets.GITHUB_TOKEN }}
